# Generated by Django 5.2.6 on 2025-09-29 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0002_inspection_inspectionitem_inventory_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the vehicle', null=True, upload_to='vehicle_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
