# Generated by Django 5.2.6 on 2025-09-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0003_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
