# Generated by Django 5.2.6 on 2025-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0004_organization_auto_backup_organization_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='job_type',
            field=models.CharField(blank=True, help_text='Type of job (engine_repair, brake_service, etc.)', max_length=50),
        ),
    ]
