# Generated by Django 5.2.6 on 2025-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0005_session_expected_end_date_session_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
