# Generated by Django 5.2.6 on 2025-10-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0007_add_inventory_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('service', 'Individual Service'), ('package', 'Service Package'), ('discount', 'Discount Offer')], default='service', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Service category (maintenance, electrical, etc.)', max_length=50)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('labor-parts', 'Labor + Parts')], default='fixed', max_length=20)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_time', models.CharField(blank=True, help_text='Estimated time (e.g., 30-45 minutes)', max_length=50)),
                ('recommended_for', models.CharField(blank=True, help_text='Recommended vehicle types', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('included_services', models.ManyToManyField(blank=True, related_name='packages', to='gixat.service')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gixat.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
