# Generated by Django 5.2.6 on 2025-10-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='client_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='client_signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='linked_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='gixat.session'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='after_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of after photo URLs'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='before_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of before photo URLs'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text='List of video URLs'),
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Template category (pre-service, post-repair, annual, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('template_items', models.JSONField(default=list, help_text='List of template checklist items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gixat.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gixat.inspectiontemplate'),
        ),
    ]
