# Generated by Django 5.2.6 on 2025-10-05 09:14

import django.db.models.deletion
from django.db import migrations, models


def convert_supplier_data(apps, schema_editor):
    Inventory = apps.get_model('gixat', 'Inventory')
    Supplier = apps.get_model('gixat', 'Supplier')
    
    # Get all unique supplier names from inventory
    supplier_names = Inventory.objects.exclude(supplier__isnull=True).exclude(supplier='').values_list('supplier', flat=True).distinct()
    
    # Create suppliers for each unique name
    supplier_map = {}
    for name in supplier_names:
        if name and name.strip():
            # Get the organization from the first inventory item with this supplier
            inventory_item = Inventory.objects.filter(supplier=name).first()
            if inventory_item:
                supplier, created = Supplier.objects.get_or_create(
                    organization=inventory_item.organization,
                    name=name.strip(),
                    defaults={
                        'is_active': True
                    }
                )
                supplier_map[name] = supplier
    
    # Update inventory records to use supplier foreign key
    for inventory_item in Inventory.objects.exclude(supplier__isnull=True).exclude(supplier=''):
        if inventory_item.supplier in supplier_map:
            inventory_item.supplier_id = supplier_map[inventory_item.supplier].id
            inventory_item.save(update_fields=['supplier_id'])


def reverse_convert_supplier_data(apps, schema_editor):
    Inventory = apps.get_model('gixat', 'Inventory')
    
    # Convert back to string representation
    for inventory_item in Inventory.objects.exclude(supplier__isnull=True):
        inventory_item.supplier = inventory_item.supplier.name
        inventory_item.save(update_fields=['supplier'])


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0009_inspection_client_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms (e.g., Net 30, COD)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gixat.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.RunPython(convert_supplier_data, reverse_convert_supplier_data),
        migrations.AlterField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gixat.supplier'),
        ),
    ]
