# Generated by Django 5.2.6 on 2025-10-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gixat', '0010_add_supplier_model'),
    ]

    operations = [
        # Add new supplier_id field
        migrations.AddField(
            model_name='inventory',
            name='supplier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gixat.supplier'),
        ),
        # Run data conversion
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        # Remove old supplier field
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        # Rename supplier_id to supplier
        migrations.RenameField(
            model_name='inventory',
            old_name='supplier_id',
            new_name='supplier',
        ),
    ]
