export enum EntryType {
  NOTE = 'NOTE',
  PHOTO = 'PHOTO',
  VOICE_NOTE = 'VOICE_NOTE',
  QUOTATION_CREATED = 'QUOTATION_CREATED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  CUSTOMER_APPROVAL = 'CUSTOMER_APPROVAL',
  JOB_STARTED = 'JOB_STARTED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE'
}