// <auto-generated />
using System;
using Gixat.Modules.Sessions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gixat.Web.Migrations.Sessions
{
    [DbContext(typeof(SessionDbContext))]
    partial class SessionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.CustomerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerConcerns")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedServices")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("CustomerRequests", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.GarageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientVehicleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedCompletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("MileageIn")
                        .HasColumnType("integer");

                    b.Property<int?>("MileageOut")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ServiceAdvisorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientVehicleId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SessionNumber");

                    b.HasIndex("Status");

                    b.HasIndex("CompanyId", "SessionNumber")
                        .IsUnique();

                    b.ToTable("GarageSessions", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrakeCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ElectricalCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EngineCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExteriorCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Findings")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("FluidLevels")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("InspectionCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InspectionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InspectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("InteriorCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OverallPriority")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuspensionCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TireCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransmissionCondition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Inspections", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.InspectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresAttention")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InspectionId");

                    b.ToTable("InspectionItems", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.JobCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualCompletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ActualHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("ActualStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAuthorizationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerAuthorizationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("CustomerAuthorized")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CustomerAuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("EstimatedCompletionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("EstimatedStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("JobCardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("PrimaryTechnicianId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("QualityNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobCardNumber");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("CompanyId", "JobCardNumber")
                        .IsUnique();

                    b.ToTable("JobCards", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.JobCardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("JobCardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("QualityCheckNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("QualityChecked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("QualityCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QualityCheckedById")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkPerformed")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobCardId");

                    b.HasIndex("Status");

                    b.ToTable("JobCardItems", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JobCardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JobCardItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("S3Bucket")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("S3Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TestDriveId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailS3Key")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerRequestId");

                    b.HasIndex("InspectionId");

                    b.HasIndex("JobCardId");

                    b.HasIndex("JobCardItemId");

                    b.HasIndex("MediaType");

                    b.HasIndex("S3Key");

                    b.HasIndex("SessionId");

                    b.HasIndex("TestDriveId");

                    b.ToTable("MediaItems", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.TestDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcPerformance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BrakePerformance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("ElectricalObservations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EnginePerformance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Findings")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("MileageEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("MileageStart")
                        .HasColumnType("integer");

                    b.Property<string>("NoiseObservations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("OverallPriority")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RouteDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SteeringPerformance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SuspensionPerformance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TransmissionPerformance")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VibrationObservations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("TestDrives", (string)null);
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.CustomerRequest", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.GarageSession", "Session")
                        .WithOne("CustomerRequest")
                        .HasForeignKey("Gixat.Modules.Sessions.Entities.CustomerRequest", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.Inspection", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.GarageSession", "Session")
                        .WithOne("Inspection")
                        .HasForeignKey("Gixat.Modules.Sessions.Entities.Inspection", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.InspectionItem", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.Inspection", "Inspection")
                        .WithMany("Items")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.JobCard", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.GarageSession", "Session")
                        .WithOne("JobCard")
                        .HasForeignKey("Gixat.Modules.Sessions.Entities.JobCard", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.JobCardItem", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.JobCard", "JobCard")
                        .WithMany("Items")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCard");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.MediaItem", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.CustomerRequest", "CustomerRequest")
                        .WithMany("MediaItems")
                        .HasForeignKey("CustomerRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gixat.Modules.Sessions.Entities.Inspection", "Inspection")
                        .WithMany("MediaItems")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gixat.Modules.Sessions.Entities.JobCard", "JobCard")
                        .WithMany("MediaItems")
                        .HasForeignKey("JobCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gixat.Modules.Sessions.Entities.JobCardItem", "JobCardItem")
                        .WithMany("MediaItems")
                        .HasForeignKey("JobCardItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gixat.Modules.Sessions.Entities.GarageSession", "Session")
                        .WithMany("MediaItems")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gixat.Modules.Sessions.Entities.TestDrive", "TestDrive")
                        .WithMany("MediaItems")
                        .HasForeignKey("TestDriveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomerRequest");

                    b.Navigation("Inspection");

                    b.Navigation("JobCard");

                    b.Navigation("JobCardItem");

                    b.Navigation("Session");

                    b.Navigation("TestDrive");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.TestDrive", b =>
                {
                    b.HasOne("Gixat.Modules.Sessions.Entities.GarageSession", "Session")
                        .WithOne("TestDrive")
                        .HasForeignKey("Gixat.Modules.Sessions.Entities.TestDrive", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.CustomerRequest", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.GarageSession", b =>
                {
                    b.Navigation("CustomerRequest");

                    b.Navigation("Inspection");

                    b.Navigation("JobCard");

                    b.Navigation("MediaItems");

                    b.Navigation("TestDrive");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.Inspection", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.JobCard", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.JobCardItem", b =>
                {
                    b.Navigation("MediaItems");
                });

            modelBuilder.Entity("Gixat.Modules.Sessions.Entities.TestDrive", b =>
                {
                    b.Navigation("MediaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
