// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs61YqBb_lw9H0qzd5KH3YEHBXgVBd240',
    appId: '1:452012051448:android:a03f42bf9c189bf38ce40d',
    messagingSenderId: '452012051448',
    projectId: 'gixat-app',
    storageBucket: 'gixat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-8Umt4Zz24yONTNOtweUmRV3OGKm16d0',
    appId: '1:452012051448:ios:a524b1fbce71484f8ce40d',
    messagingSenderId: '452012051448',
    projectId: 'gixat-app',
    storageBucket: 'gixat-app.firebasestorage.app',
    androidClientId: '452012051448-4og529gm81478d1pgndf753bfiav0j73.apps.googleusercontent.com',
    iosClientId: '452012051448-rjb7js2o2k6he5e7vqu4pngh0i34227i.apps.googleusercontent.com',
    iosBundleId: 'com.roxate.gixat',
  );
}
